#!/usr/bin/env python3
"""Based on the TX-MS web-app implementation Cheetah-MS.
"""

__author__ = 'Joel Ströbaek'
__email__ = 'joel.strobaek@gmail.com'


# TODO:
# - Remove ms2 parameter hard coding!
#       - Set optional click input params with defaults
# - Look into adding logs for all the rules
#       - Diverting STDOUT/STDERR to log files
# - Set temp files
#       - dock_tmp.pdb / lig_tmp.pdb
#       - pdb_A/B.pdb
# - Add some subfolders to the results dir
#       - supp_files: all_xls.txt, antibody/antigen_seq.txt, detected_spectra.txt,
#                     antibody/antigen.pdb
# - MAKE A BETTER FOLDER STRUCTURE FOR THE OUTPUT
# - REMOVE ALL THE HARD CODING!
# - Refactor the scripts and workflow to actually make it fully modular...
#       - Many of the steps are interwoven in the current iteration,
#         which (e.g.) inhibits an easy change of docking software
# - SAVE THE FILTERED MGF IN samples/filtered_mgf/
# - RENAME THE megadock.out FILE?
# - FIX THE MEGADOCK BLOCKING SCRIPT TO BE A BIT MORE FLEXIBLE (+/- few AAs)

import os
from glob import glob
from pathlib import Path

import pandas as pd
from snakemake.utils import min_version


def get_linker_num(wildcards):

    linker_nums = {'DSS': 1,
                   'DSG': 2,
                   'ESG': 3}

    sample_to_linker = dict(zip(SAMPLES, LINKERS))

    linker_name = sample_to_linker[wildcards.sample]

    return linker_nums[linker_name]

def get_unique_pairs(df, with_samples=False):

    get_antibody_id = lambda x: '_'.join(x.split('_')[:-1])

    df['antibody_id'] = df['antibody'].apply(get_antibody_id)

    if with_samples:

        unique_pairs = df[['antigen',
                           'antibody_id', 'sample']].drop_duplicates()

    else:

        unique_pairs = df[['antigen', 'antibody_id']].drop_duplicates()

    return [tuple(p) for p in unique_pairs.values.tolist()]


min_version("6.0")  # Min version for using modules.

configfile: "config/config_2.yml"


WD = Path(workflow.snakefile).parent

# Convert config paths from string to Path objects.
config_paths = ['output_dir', 'antibody_dir', 'antigen_dir', 'ms2_file']

config = {k: (v if k not in config_paths else Path(v).resolve())
          for k, v in config.items()}

OUTDIR_BASE = config['output_dir']

BLOCK_FV = bool(config['block_antibody_non_CDR'])

table_file = config.get('table_file', 'config/entries_2.csv')

df = pd.read_csv(table_file)

ANTIGEN_LIST, ANTIBODY_LIST, SAMPLES, LINKERS = df.values.T

# Create a new dataframe containing only unique antigen-antibody pairs
unique_pairs_df = df[['antigen', 'antibody', 'sample']].drop_duplicates()
# Create new lists from this unique dataframe
ANTIGEN_LIST = unique_pairs_df['antigen'].to_list()

UNIQUE_ANTIBODY_LIST = unique_pairs_df['antibody'].to_list()

UNIQUE_PAIRS = get_unique_pairs(unique_pairs_df)

SAMPLE_MAPPING = get_unique_pairs(df, with_samples=True)

AB_ID_TO_REP = df.drop_duplicates('antibody_id').set_index('antibody_id')['antibody'].to_dict()

UNIQUE_ANTIBODY_IDS = list(AB_ID_TO_REP.keys())

BEST_PDB = ['best_model.pdb'] * len(ANTIGEN_LIST)

BEST_TXT = ['best_model_xls.txt'] * len(ANTIGEN_LIST)

SUPPORT_FILES = 'structure_module/supporting_files'

DOCKING_FILES = 'structure_module/docking'

DATA_FILES = 'data_module/sample_files'

SCORE_FILES = 'scoring_module'


rule all:
    input:
        expand(os.path.join(OUTDIR_BASE,
                             DOCKING_FILES,
                             "{antigen}_+_{antibody}",
                             "{antigen}_+_{antibody}_megadock.done"),
               zip,
               antigen=ANTIGEN_LIST, antibody=UNIQUE_ANTIBODY_LIST),
        expand(os.path.join(OUTDIR_BASE,
                             SUPPORT_FILES,
                             "{antigen}_+_{antibody_id}.xls"),
               zip,
               antigen=ANTIGEN_LIST, antibody_id=UNIQUE_ANTIBODY_IDS),
        expand(os.path.join(OUTDIR_BASE,
                            SCORE_FILES,
                            "{sample}",
                            "{antigen}_+_{antibody_id}",
                            "spectra_annotation.sql"),
               zip,
               sample=SAMPLES,
               antigen=ANTIGEN_LIST, antibody_id=UNIQUE_ANTIBODY_IDS),
        # expand(
        #     os.path.join(
        #         OUTDIR_BASE, 'scoring_module',
        #         "{sample}",
        #         "{antigen}",
        #         "{antibody}",
        #         "{best_txt}"
        #      ),
        #      zip,
        #      sample=SAMPLES,
        #      antigen=ANTIGEN_LIST,
        #      antibody=ANTIBODY_LIST,
        #      best_txt=BEST_TXT
        # )

include: 'rules/structure_module.smk'

include: 'rules/data_module.smk'

# rule data2mzML:
#     # TODO:
#     #   - Sort proper thermoRawFileParser inclusion
#     input:
#         ms2 = os.path.join(config["ms2_files"],
#                            f"{{sample}}{config['ms2_ext']}")
#     output:
#         mzml = os.path.join(OUTDIR_BASE,
#                            'data_module', "input_mzML", "{sample}.mzML")
#     params:
#         outdir = os.path.join(OUTDIR_BASE, 'data_module', "input_mzML"),
#         thermoRawFileParser = config['thermoRawFileParser']
#     conda:
#         'envs/mono_env.yml'
#     shell:
#         "[[ $(sed 's/^.*\.//' <(echo {input.ms2})) == mzML ]]"
#         " &&"
#         " ln -s {input.ms2} {output.mzml}"
#         " ||"
#         " mono {params.thermoRawFileParser}"
#         " -i={input.ms2}"
#         " -o={params.outdir}"
#         " -f=2"

# rule CSM_annotation:
#     input:
#         mzml = rules.data2mzML.output.mzml,
#         xls = rules.seq2xl.output
#     output:
#         sql = os.path.join(OUTDIR_BASE,
#                            'data_module',
#                            "{sample}",
#                            "{antigen}", "{antibody}", "ms2_results.sql"),
#         img_dir = directory(os.path.join(OUTDIR_BASE,
#                                          'data_module',
#                                          "{sample}",
#                                          "{antigen}",
#                                          "{antibody}", "top_spectra")),
#         top_xls = os.path.join(OUTDIR_BASE,
#                                'data_module',
#                                "{sample}",
#                                "{antigen}", "{antibody}", "top_xls.txt"),
#         mgf_filt = os.path.join(OUTDIR_BASE,
#                                 'data_module',
#                                 "{sample}",
#                                 "{antigen}",
#                                 "{antibody}", "{sample}_filtered.mgf")
#     params:
#         ms_search_script = 'workflow/scripts/sidewinder-ms_v2.py',
#         x_linker = get_linker_num,
#         mass_delta_cutoff = 0.01,
#         outdir = os.path.join(OUTDIR_BASE,
#                               'data_module', "{sample}", "{antigen}", "{antibody}")
#     conda:
#         'envs/pyteomics_env.yml'
#     shell:
#         "python3 {params.ms_search_script} "
#         "--mzml_file {input.mzml} "
#         # "--mgf_file {input.mgf} "
#         "--xl_file {input.xls} "
#         "--x_linker {params.x_linker} "
#         "--mass_delta_cutoff {params.mass_delta_cutoff} "
#         "--output_dir {params.outdir}"

# include: 'rules/scoring_module.smk'

# rule modeling:
#     # TODO:
#     #   - Save euclidean distances to file
#     #       - Include aa-numbering and xyz-coord anchors
#     #   - Set container image from config.
#     input:
#         pdb_a = rules.pdb_handling.output.pdb_a,
#         pdb_b = rules.pdb_handling.output.pdb_b,
#         top_xls = rules.CSM_annotation.output.top_xls,
#         dock_file = rules.molecular_docking.output
#     output:
#         top_model = os.path.join(OUTDIR_BASE,
#                                  'scoring_module',
#                                  "{sample}",
#                                  "{antigen}", "{antibody}", "best_model.pdb" ),
#         top_xls = os.path.join(OUTDIR_BASE,
#                                'scoring_module',
#                                "{sample}",
#                                "{antigen}", "{antibody}", "best_model_xls.txt"),
#         scores = os.path.join(OUTDIR_BASE,
#                               'scoring_module',
#                               "{sample}",
#                               "{antigen}", "{antibody}", "scores.csv")
#     params:
#         cut_off = config['distance_cut_off'],
#         n_top_f = config['num_of_top_filters'],
#         n_docks = config['model_samples'],
#         modeling_script = 'workflow/scripts/sidewinder-model.py',
#         outdir = os.path.join(OUTDIR_BASE,
#                               'scoring_module',
#                               "{sample}", "{antigen}", "{antibody}")
#     conda:
#         'envs/biopython_env.yml'
#     threads:
#         round(workflow.cores * 0.10)
#     shell:
#         "python3 {params.modeling_script} "
#         "--pdb_a {input.pdb_a} "
#         "--pdb_b {input.pdb_b} "
#         "--output_dir {params.outdir} "
#         "--top_xls_file {input.top_xls} "
#         "--dock_file {input.dock_file} "
#         "--n_models {params.n_docks} "
#         "--n_filters {params.n_top_f} "
#         "--cut_off {params.cut_off}"
