## USER configurable options:

# Default output_dir: 'results/{date}'
output_dir: '/srv/data1/home/jo0348st/projects/2023-di_heusel_m1_mAbs/results/txms/240906-m1_anchorless_scFab'

# Antibody dir:
targets_dir: '/srv/data1/home/jo0348st/projects/2023-di_heusel_m1_mAbs/results/colabfold/240831_scaffold_mAbs/relaxed_pdbs/sc-mAbs'

# Antigen dir:
binders_dir: '/srv/data1/home/jo0348st/projects/2023-di_heusel_m1_mAbs/results/colabfold/240831_scaffold_mAbs/relaxed_pdbs/m1'

# Path where all samples are stored. Valid formats: [raw, mzml, mgf]
ms2_files:  '/srv/data1/home/jo0348st/data/2023-di_heusel_m1_mAbs/xlms/candidate_xlms/mzML'
ms2_ext: '.mzML'

distance_cut_off: 32  # In Ångström
num_of_top_filters: 10  # Models to keep
model_samples: 100  # Cheetah-default=10, max=docking_samples
docking_samples: 2000  # Default 2000

block_antibody_non_CDR: True

# Options: 1=DSS, 2=DSG, 3=EGS
x_linker: 1  # Move option to CSV!

## STATIC configuration (NOT user specified):

thermoRawFileParser: '/srv/data1/home/jo0348st/src/thermoRawFileParser/ThermoRawFileParser.exe'
