# User configurable options:

# Default output_dir: 'results/{date}'
output_dir: '/path/to/output_directory'

input_pdb1: '/path/to/input_pdb_1'
input_pdb2: '/path/to/input_pdb_2'

input_ms2: '/path/to/input_ms2_file'  # Valid formats: [mzml, mgf]

distance_cut_off: 30  # In Ångström
num_of_top_filters: 2
